CREATE TABLE IF NOT EXISTS flights (
    flight_id      VARCHAR(10)  PRIMARY KEY,
    from_airport   VARCHAR(100),
    to_airport     VARCHAR(100),
    speed_kmh      INTEGER,
    altitude_ft    INTEGER,
    departure      VARCHAR(20),
    arrival        VARCHAR(20),
    aircraft       VARCHAR(50),
    status         VARCHAR(20),
    updated_at     TIMESTAMP,
    lat            DOUBLE PRECISION,
    lng            DOUBLE PRECISION,
    heading        INTEGER,
    prev_altitude_ft INTEGER,
    v_speed_fpm    INTEGER,
    flight_icao    VARCHAR(20),
    dep_gate       VARCHAR(20),
    arr_gate       VARCHAR(20),
    dep_terminal   VARCHAR(20),
    arr_terminal   VARCHAR(20),
    arr_baggage    VARCHAR(20),
    dep_delayed    INTEGER,
    arr_delayed    INTEGER,
    dep_estimated  VARCHAR(20),
    arr_estimated  VARCHAR(20)
);
